In [1]:
## Inputs: 
## - mapping -- 10x20 mat where each cell value reps the control value/index
## - mask    -- 10x20 mat where 5x5 block of ones indicate the control/actuation focus
## - control -- 5x5 mat to be applied to mask focus


## Output:
## - control_dict -- dict with keys(1-30) of control

In [59]:
import numpy as np
from math import floor, ceil

## control
np.random.seed(1)
control = np.random.randint(0, 10, (5,5))
print("Control")
display(control)

## mapping

print("Mapping")
display(mapping)

## mask
centroid = (5,4)
mask_width = 5
n_cols, n_rows = 12, 10
fixed_size = (n_rows, n_cols)

def maskFromCentroid(centroid):
    x, y = centroid
    
    x_min = max(0, x - floor(mask_width/2))
    x_max = min(n_cols, x + ceil(mask_width/2))
    
    y_min = max(0, y - floor(mask_width/2))
    y_max = min(n_rows, y + ceil(mask_width/2))
    
    mask = np.zeros((fixed_size))
    mask[y_min:y_max, x_min:x_max] = 1
    
    return mask
mask = maskFromCentroid(centroid)
print("Mask")
display(mask)

Control


array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9]])

Mapping


array([[ 5, 10, 15, 20, 25, 30,  5, 10, 15, 20, 25, 30],
       [ 4,  9, 14, 19, 24, 29,  4,  9, 14, 19, 24, 29],
       [ 3,  8, 13, 18, 23, 28,  3,  8, 13, 18, 23, 28],
       [ 2,  7, 12, 17, 22, 27,  2,  7, 12, 17, 22, 27],
       [ 1,  6, 11, 16, 21, 26,  1,  6, 11, 16, 21, 26],
       [ 5, 10, 15, 20, 25, 30,  5, 10, 15, 20, 25, 30],
       [ 4,  9, 14, 19, 24, 29,  4,  9, 14, 19, 24, 29],
       [ 3,  8, 13, 18, 23, 28,  3,  8, 13, 18, 23, 28],
       [ 2,  7, 12, 17, 22, 27,  2,  7, 12, 17, 22, 27],
       [ 1,  6, 11, 16, 21, 26,  1,  6, 11, 16, 21, 26]], dtype=int8)

Mask


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
control_mask = np.zeros((10,12), dtype=int)
control_mask[mask.nonzero()] = control.flatten()
print("control_mask: ")
print(control_mask)
print()

mapping[mask==0] = 0
print("mapping: ")
print(mapping)
print()

control_idxs = mapping[mask>0]
print("control_idxs")
print(control_idxs)
print(" ")

control_vals = control_mask[mask>0]
print("control_vals: ")
print(control_vals)
print()

control_dict = {}
for i,v in enumerate(control_idxs):
    control_dict[v] = control_vals[i]
    print(i, v, control_vals[i])
    
print(control_dict)

control_mask: 
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 5 8 9 5 0 0 0 0 0]
 [0 0 0 0 1 7 6 9 0 0 0 0]
 [0 0 0 2 4 5 2 4 0 0 0 0]
 [0 0 0 2 4 7 7 9 0 0 0 0]
 [0 0 0 1 7 0 6 9 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]

mapping: 
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18 23 28  3  8  0  0  0  0]
 [ 0  0  0 17 22 27  2  7  0  0  0  0]
 [ 0  0  0 16 21 26  1  6  0  0  0  0]
 [ 0  0  0 20 25 30  5 10  0  0  0  0]
 [ 0  0  0 19 24 29  4  9  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]

control_idxs
[18 23 28  3  8 17 22 27  2  7 16 21 26  1  6 20 25 30  5 10 19 24 29  4
  9]
 
control_vals: 
[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6 9]

0 18 5
1 23 8
2 28 9
3 3 5
4 8 0
5 17 0
6 22 1
7 27 7
8 2 6
9 7 9
10 16 2
11 21 4
12 26 5
13 1 2
14 6 4
15 20 2
16 25 4
17 30 7
18 5 7
19 10 9
20 19 1

In [78]:
control_mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 8., 9., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 7., 6., 9., 0., 0., 0., 0.],
       [0., 0., 0., 2., 4., 5., 2., 4., 0., 0., 0., 0.],
       [0., 0., 0., 2., 4., 7., 7., 9., 0., 0., 0., 0.],
       [0., 0., 0., 1., 7., 0., 6., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])