In [1]:
## Inputs: 
## - mapping -- 10x20 mat where each cell value reps the control value/index
## - mask    -- 10x20 mat where 5x5 block of ones indicate the control/actuation focus
## - control -- 5x5 mat to be applied to mask focus


## Output:
## - control_dict -- dict with keys(1-30) of control


## Edits:
## Accounting for the masks that partly spill out of the original mapping 

In [23]:
import numpy as np
from math import floor, ceil



## control
np.random.seed(1)
control = np.random.randint(0, 10, (5,5))
print("Control")
display(control)

## mapping
fixed_size = (10,12)
adjusted_size = (fixed_size[0]+4, fixed_size[1]+4)
n_rows, n_cols = fixed_size
# adjusted_rows, adjusted_cols = adjusted_size
# mapping = np.zeros(fixed_size, dtype=np.int8)
mapping = np.zeros(adjusted_size, dtype=np.int8)
submap = np.zeros((int(n_rows/2), int(n_cols/2)))

submap[:, 0] = np.arange(5, 0, -1)#.reshape((n_rows/2, 1))
submap[:, 1] = np.arange(10, 5, -1)#.reshape((n_rows/2, 1))
submap[:, 2] = np.arange(15, 10, -1)#.reshape((n_rows/2, 1))
submap[:, 3] = np.arange(20, 15, -1)#.reshape((n_rows/2, 1))
submap[:, 4] = np.arange(25, 20, -1)#.reshape((n_rows/2, 1))
submap[:, 5] = np.arange(30, 25, -1)#.reshape((n_rows/2, 1))

# mapping[0:5, 0:6] = submap
# mapping[0:5, 6:12] = submap
# mapping[5:10, 0:6] = submap
# mapping[5:10, 6:12] = submap

mapping[2:7, 2:8] = submap
mapping[2:7, 8:14] = submap
mapping[7:12, 2:8] = submap
mapping[7:12, 8:14] = submap
print("Mapping")
display(mapping)

## mask
centroid = (9+2, 11+2)
mask_width = 5
n_cols, n_rows = 12+4, 10+4
fixed_size = (n_rows, n_cols)

def maskFromCentroid(centroid):
    y, x = centroid
    
    x_min = max(0, x - floor(mask_width/2))
    x_max = min(n_cols, x + ceil(mask_width/2))
    
    y_min = max(0, y - floor(mask_width/2))
    y_max = min(n_rows, y + ceil(mask_width/2))
    
    mask = np.zeros((fixed_size))
    mask[y_min:y_max, x_min:x_max] = 1
    
    return mask
mask = maskFromCentroid(centroid)
print("Mask")
display(mask)

Control


array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9]])

Mapping


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5, 10, 15, 20, 25, 30,  5, 10, 15, 20, 25, 30,  0,  0],
       [ 0,  0,  4,  9, 14, 19, 24, 29,  4,  9, 14, 19, 24, 29,  0,  0],
       [ 0,  0,  3,  8, 13, 18, 23, 28,  3,  8, 13, 18, 23, 28,  0,  0],
       [ 0,  0,  2,  7, 12, 17, 22, 27,  2,  7, 12, 17, 22, 27,  0,  0],
       [ 0,  0,  1,  6, 11, 16, 21, 26,  1,  6, 11, 16, 21, 26,  0,  0],
       [ 0,  0,  5, 10, 15, 20, 25, 30,  5, 10, 15, 20, 25, 30,  0,  0],
       [ 0,  0,  4,  9, 14, 19, 24, 29,  4,  9, 14, 19, 24, 29,  0,  0],
       [ 0,  0,  3,  8, 13, 18, 23, 28,  3,  8, 13, 18, 23, 28,  0,  0],
       [ 0,  0,  2,  7, 12, 17, 22, 27,  2,  7, 12, 17, 22, 27,  0,  0],
       [ 0,  0,  1,  6, 11, 16, 21, 26,  1,  6, 11, 16, 21, 26,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

Mask


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [24]:
control_mask = np.zeros((14,16), dtype=int)
control_mask[mask.nonzero()] = control.flatten()
print("control_mask: ")
print(control_mask)
print()

mapping[mask==0] = 0
print("mapping: ")
print(mapping)
print()

control_idxs = mapping[mask>0]
print("control_idxs")
print(control_idxs)
print(" ")

control_vals = control_mask[mask>0]
print("control_vals: ")
print(control_vals)
print()

control_dict = {}
for i,v in enumerate(control_idxs):
    control_dict[v] = control_vals[i]
    print(i, v, control_vals[i])

control_dict.pop(0)
    
print(control_dict)

control_mask: 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 5 8 9 5 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 7 6 9]
 [0 0 0 0 0 0 0 0 0 0 0 2 4 5 2 4]
 [0 0 0 0 0 0 0 0 0 0 0 2 4 7 7 9]
 [0 0 0 0 0 0 0 0 0 0 0 1 7 0 6 9]]

mapping: 
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  

In [25]:
print("control_dict")
print(len(control_dict))
print(control_dict)
print()
print("control_idxs")
print(len(control_idxs))
print(control_idxs)
print()
print("control_vals")
print(len(control_vals))
print(control_vals)

control_dict
9
{18: 5, 23: 8, 28: 9, 17: 0, 22: 1, 27: 7, 16: 2, 21: 4, 26: 5}

control_idxs
25
[18 23 28  0  0 17 22 27  0  0 16 21 26  0  0  0  0  0  0  0  0  0  0  0
  0]

control_vals
25
[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6 9]
