In [27]:
## Generating Control Matrices
## by using a variable inter-column delta

import numpy as np


def genColumnsByDelta(delta=15, shape=(5,5), start=0, zero_borders=False):
    
    zero_mat = np.zeros(shape, dtype=int)
    
    if zero_borders:
        shape = shape[0]-2, shape[1]-2
        
    mat = np.zeros((shape), dtype=int)
    
    for i in range(shape[1]):
        col = np.ones((shape[0]))*(start + i*delta)
        mat[:,i] = col
        
    if zero_borders:
        zero_mat[1:shape[0]+1, 1:shape[1]+1] = mat[:,:]
        return zero_mat
        
    return mat

def genRowsByDelta(delta=15, shape=(5,5), start=4, zero_borders=False):
    
    zero_mat = np.zeros(shape, dtype=int)
    
    if zero_borders:
        shape = shape[0]-2, shape[1]-2

    
    mat = np.zeros((shape), dtype=int)
    
    for i in range(shape[0]):
        row = np.ones((shape[1]))*(start + i*delta)
        mat[i, :] = row

        
    if zero_borders:
        zero_mat[1:shape[0]+1, 1:shape[1]+1] = mat[:,:]
        return zero_mat
        
    return mat

def zeroOutBorderCells(mat=np.ones((5,5), dtype=int)):
    
    n_rows, n_cols = mat.shape
    mat[0] = mat[:,0] = mat[n_rows-1] = mat[:, n_cols-1] = 0
    return mat
    


print(genColumnsByDelta(zero_borders=True))
print()
print(genColumnsByDelta())
print()

print(genRowsByDelta(zero_borders=True))
print()
print(genRowsByDelta())
print()

print(zeroOutBorderCells())
print()    
    

[[ 0  0  0  0  0]
 [ 0  0 15 30  0]
 [ 0  0 15 30  0]
 [ 0  0 15 30  0]
 [ 0  0  0  0  0]]

[[ 0 15 30 45 60]
 [ 0 15 30 45 60]
 [ 0 15 30 45 60]
 [ 0 15 30 45 60]
 [ 0 15 30 45 60]]

[[ 0  0  0  0  0]
 [ 0  4  4  4  0]
 [ 0 19 19 19  0]
 [ 0 34 34 34  0]
 [ 0  0  0  0  0]]

[[ 4  4  4  4  4]
 [19 19 19 19 19]
 [34 34 34 34 34]
 [49 49 49 49 49]
 [64 64 64 64 64]]

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

